version: "3.9"

services:
  db:
    image: postgres:15
    container_name: merge_automator_db
    environment:
      POSTGRES_USER: merge_user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: merge_automator
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
